/**
 * PE drill catalog. Sessions reference drills by id.
 * Content from docs/PowerEndurance_Trainer/ plan documents.
 */

import type { PEDrillDefinition } from "./types";

const DRILLS: Record<string, Omit<PEDrillDefinition, "id">> = {
  warmup_progressive: {
    type: "warmup",
    name: "Progressive Warm-Up",
    description: "15-20 min easy climbing, then progressive hangs",
    instructions: [
      "10-15 min easy climbing (3-4 grades below max)",
      "Progressive hangs: bodyweight → 50% → 75% → 85% of target load",
      "Arm circles, scapular activation, finger flexion/extension",
    ],
    notes: [],
    isOptional: false,
    safetyWarnings: ["Never skip warm-up before max hangs"],
    progressionRules: [],
  },

  warmup_easy: {
    type: "warmup",
    name: "Easy Warm-Up",
    description: "10 min very easy climbing",
    instructions: ["10 min very easy climbing at RPE 3-4", "Light movement prep"],
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  warmup_silent_feet: {
    type: "warmup",
    name: "Warm-Up with Silent Feet Primer",
    description: "Standard warm-up; silent feet rule in final 5-10 min",
    instructions: [
      "10-15 min progressive warm-up",
      "Last 5-10 min: every foot placement silent and one-and-done",
    ],
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  warmup_short: {
    type: "warmup",
    name: "Short Warm-Up",
    description: "15 min easy climbing + progressive hangs",
    instructions: ["10-15 min easy climbing", "Progressive hangs to 75% target"],
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  max_hang_pe_w1: {
    type: "max_hang",
    name: "Max Hangs",
    description: "6 × 10s at 85% of tested max",
    instructions: [
      "20-22mm edge, half-crimp grip",
      "6 sets × 10 seconds at 85%; 2-3 min rest",
      "Stop if pain > 2/10 or form breaks",
    ],
    sets: 6,
    reps: "10 seconds",
    intensity: "85%",
    restSeconds: 120,
    notes: [],
    isOptional: false,
    safetyWarnings: ["Never progress load and volume in the same week"],
    progressionRules: ["All 6 reps clean for 2 sessions → add 2-3% load"],
  },

  max_hang_pe_w2: {
    type: "max_hang",
    name: "Max Hangs",
    description: "6 × 10s at 88-90% of tested max",
    instructions: ["6 sets × 10s at 88-90%; 2-3 min rest"],
    sets: 6,
    reps: "10 seconds",
    intensity: "88-90%",
    restSeconds: 120,
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  max_hang_pe_w3: {
    type: "max_hang",
    name: "Max Hangs",
    description: "6 × 10s at 90-93% of tested max",
    instructions: ["6 sets × 10s at 90-93%; 2-3 min rest"],
    sets: 6,
    reps: "10 seconds",
    intensity: "90-93%",
    restSeconds: 120,
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  max_hang_maintenance: {
    type: "max_hang",
    name: "Maintenance Max Hangs",
    description: "4-5 sets × 10s at 85-90% — maintain, not build",
    instructions: [
      "4-5 sets × 10 seconds at 85-90%",
      "Focus on perfect form; 2-3 min rest",
    ],
    sets: 5,
    reps: "10 seconds",
    intensity: "85-90%",
    restSeconds: 150,
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  max_hang_retest: {
    type: "max_hang_retest",
    name: "Max Hang Retest",
    description: "Retest max hang load (deload / test weeks)",
    instructions: ["Same protocol as Week 0 assessment", "Record best 7s hang"],
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  max_hang_deload: {
    type: "max_hang",
    name: "Deload Max Hangs",
    description: "4 × 10s at 85%",
    instructions: ["Reduced volume deload session"],
    sets: 4,
    reps: "10 seconds",
    intensity: "85%",
    restSeconds: 120,
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  pull_up_heavy: {
    type: "pull_up",
    name: "Heavy Pulling Strength",
    description: "4 sets × 3-5 reps weighted pull-ups",
    instructions: [
      "10 min rest after hangs",
      "4 sets × 3-5 reps at heavy load; 3 min rest",
    ],
    sets: 4,
    reps: "3-5",
    restSeconds: 180,
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: ["Add 2-5 lbs when all sets hit target reps cleanly"],
  },

  pull_up_maintenance: {
    type: "pull_up",
    name: "Maintenance Pull-Ups",
    description: "3 sets × 3-5 reps — maintain strength",
    instructions: ["3 sets at working weight; 3 min rest"],
    sets: 3,
    reps: "3-5",
    restSeconds: 180,
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  antagonist_circuit: {
    type: "antagonist",
    name: "Antagonist + Shoulder Stability",
    description: "2-round shoulder injury-prevention circuit",
    instructions: [
      "Scapular push-ups: 8-12",
      "Band external rotations: 12-20 each side",
      "Face pulls: 10-15",
      "Push-ups: 8-12",
      "Y-T-W raises: 6-10 each",
      "Hollow hold 20-40s + side plank 20-40s each side",
      "Track shoulder symptom score (0-10)",
    ],
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  antagonist_light: {
    type: "antagonist",
    name: "Light Antagonist Circuit",
    description: "1 round antagonist circuit (deload)",
    instructions: ["Single round of antagonist + shoulder stability work"],
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  arc_meso1_w1: {
    type: "arc_climbing",
    name: "ARC: Silent Feet + Fluency",
    description: "2 × 15 min continuous climbing, RPE 4-6",
    instructions: [
      "Silent feet: every placement silent and one-and-done",
      "Fluency: no stop >2s unless at designated rest hold",
      "Log slip count and stop count per set",
      "Must stay RPE 4-6 — if pumped, you're going too hard",
    ],
    sets: 2,
    reps: "15 min",
    intensity: "RPE 4-6",
    notes: [],
    isOptional: false,
    safetyWarnings: ["This must feel like recovery, not training hard"],
    progressionRules: [],
  },

  arc_meso1_w2: {
    type: "arc_climbing",
    name: "ARC: Silent Feet + Fluency",
    description: "2 × 18 min continuous climbing, RPE 4-6",
    instructions: ["Same constraints as Week 1; increased duration"],
    sets: 2,
    reps: "18 min",
    intensity: "RPE 4-6",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  arc_meso1_w3: {
    type: "arc_climbing",
    name: "ARC: Silent Feet + Fluency",
    description: "3 × 15 min continuous climbing, RPE 4-6",
    instructions: ["Same constraints; third set added"],
    sets: 3,
    reps: "15 min",
    intensity: "RPE 4-6",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  arc_meso2_w5: {
    type: "arc_climbing",
    name: "ARC Aerobic Base",
    description: "3 × 15 min, RPE 4-6",
    instructions: ["Maintain silent feet + fluency constraints"],
    sets: 3,
    reps: "15 min",
    intensity: "RPE 4-6",
    notes: [],
    isOptional: false,
    safetyWarnings: ["Do not let this session become hard"],
    progressionRules: [],
  },

  arc_meso2_w6: {
    type: "arc_climbing",
    name: "ARC Aerobic Base",
    description: "2 × 22 min, RPE 4-6",
    instructions: ["Longer sets; same constraints"],
    sets: 2,
    reps: "22 min",
    intensity: "RPE 4-6",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  arc_meso2_w7: {
    type: "arc_climbing",
    name: "ARC Aerobic Base",
    description: "3 × 18 min, RPE 4-6",
    instructions: ["Maintain low intensity throughout"],
    sets: 3,
    reps: "18 min",
    intensity: "RPE 4-6",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  arc_deload: {
    type: "arc_climbing",
    name: "Deload ARC",
    description: "1 × 20 min with constraints",
    instructions: ["Single set; silent feet + fluency active"],
    sets: 1,
    reps: "20 min",
    intensity: "RPE 4-6",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  arc_recovery: {
    type: "arc_climbing",
    name: "Active Recovery Climbing",
    description: "30-40 min very easy climbing, RPE 3-4",
    instructions: ["Silent feet throughout", "Focus on movement quality"],
    sets: 1,
    reps: "30-40 min",
    intensity: "RPE 3-4",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  four_by_four_w1: {
    type: "four_by_four",
    name: "Bouldering 4×4",
    description: "2 rounds; 4 problems 2-4 grades below limit",
    instructions: [
      "4 problems × 4 reps each; 10-12 min rest between rounds",
      "RPE 8-9; late reps shaky but not failing every time",
    ],
    sets: 2,
    reps: "4 problems × 4",
    intensity: "RPE 8-9",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: ["Add a round before raising difficulty"],
  },

  four_by_four_w2: {
    type: "four_by_four",
    name: "Bouldering 4×4",
    description: "2 rounds; slightly harder problems",
    instructions: ["Same structure; bump problem difficulty slightly"],
    sets: 2,
    reps: "4 problems × 4",
    intensity: "RPE 8-9",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  four_by_four_w3: {
    type: "four_by_four",
    name: "Bouldering 4×4",
    description: "3 rounds",
    instructions: ["Third round added when 2 rounds are clean"],
    sets: 3,
    reps: "4 problems × 4",
    intensity: "RPE 8-9",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  route_intervals_w1: {
    type: "intervals",
    name: "Route-Style Intervals",
    description: "1 set × 4 × 60s; 1:1 rest; RPE 8-9",
    instructions: ["Hard climbing intervals with equal rest"],
    sets: 1,
    reps: "4 × 60s",
    intensity: "RPE 8-9",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  route_intervals_w2: {
    type: "intervals",
    name: "Route-Style Intervals",
    description: "1 set × 5 × 75s",
    instructions: ["Increase interval duration"],
    sets: 1,
    reps: "5 × 75s",
    intensity: "RPE 8-9",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  route_intervals_w3: {
    type: "intervals",
    name: "Route-Style Intervals",
    description: "2 sets × 4 × 60s",
    instructions: ["Second set added; 8-10 min between sets"],
    sets: 2,
    reps: "4 × 60s",
    intensity: "RPE 8-9",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  route_intervals_deload: {
    type: "intervals",
    name: "Deload Intervals",
    description: "1 set × 4 × 60s",
    instructions: ["Reduced volume deload"],
    sets: 1,
    reps: "4 × 60s",
    intensity: "RPE 7-8",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  core_circuit: {
    type: "core",
    name: "Core Conditioning",
    description: "Plank, knee raises, side plank",
    instructions: [
      "Front plank: 3 × 45-60s",
      "Hanging knee raises: 3 × 10-12",
      "Side plank: 2 × 30s each side",
    ],
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  caf_meso1_w1: {
    type: "crux_after_fatigue",
    name: "Crux-After-Fatigue Drill",
    description: "5 rounds; 2-min lead-in; 6-12 move crux",
    instructions: [
      "Part A: 2 min continuous moderate climbing",
      "Part B immediately: attempt crux at RPE 9",
      "Rest 10-12 min between rounds",
      "Log pump before crux, moves, success, quality",
    ],
    sets: 5,
    reps: "2-min lead-in + crux",
    intensity: "RPE 9 crux",
    notes: [],
    isOptional: false,
    safetyWarnings: ["Primary KPI — log every round honestly"],
    progressionRules: [
      "Increase lead-in duration first",
      "Then add rounds when success rate >60%",
    ],
  },

  caf_meso1_w2: {
    type: "crux_after_fatigue",
    name: "Crux-After-Fatigue Drill",
    description: "5 rounds; 2.5-min lead-in",
    instructions: ["Extended lead-in; same crux difficulty"],
    sets: 5,
    reps: "2.5-min lead-in + crux",
    intensity: "RPE 9 crux",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  caf_meso1_w3: {
    type: "crux_after_fatigue",
    name: "Crux-After-Fatigue Drill",
    description: "6 rounds; 3-min lead-in",
    instructions: ["Sixth round added; 3-min lead-in"],
    sets: 6,
    reps: "3-min lead-in + crux",
    intensity: "RPE 9 crux",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  caf_meso2_w5: {
    type: "crux_after_fatigue",
    name: "Enhanced Crux-After-Fatigue",
    description: "5 rounds; 3-min lead-in; harder crux (+1 grade)",
    instructions: ["Practice efficient shaking during lead-in"],
    sets: 5,
    reps: "3-min lead-in + crux",
    intensity: "RPE 9 crux",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  caf_meso2_w6: {
    type: "crux_after_fatigue",
    name: "Enhanced Crux-After-Fatigue",
    description: "5 rounds; 3.5-min lead-in",
    instructions: ["Experiment with pacing and rest positions"],
    sets: 5,
    reps: "3.5-min lead-in + crux",
    intensity: "RPE 9 crux",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  caf_meso2_w7: {
    type: "crux_after_fatigue",
    name: "Enhanced Crux-After-Fatigue",
    description: "6 rounds; 4-min lead-in",
    instructions: ["Compare success rate to Mesocycle 1"],
    sets: 6,
    reps: "4-min lead-in + crux",
    intensity: "RPE 9 crux",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  campus_pe: {
    type: "campus",
    name: "Campus Board Power Work",
    description: "Max reach ladders and controlled doubles",
    instructions: [
      "2 exercises per session; 4 sets each; 2-3 min rest",
      "Maximum velocity; stop on sharp pain",
    ],
    sets: 4,
    notes: [],
    isOptional: false,
    safetyWarnings: ["Skip if finger or shoulder pain elevated"],
    progressionRules: [],
  },

  campus_deload: {
    type: "campus",
    name: "Light Campus Work",
    description: "2 sets campus (deload)",
    instructions: ["Reduced volume maintenance"],
    sets: 2,
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  intermittent_hang_w5: {
    type: "intermittent_hang",
    name: "Intermittent Hang Endurance (IHE)",
    description: "60% MVC; 7s on / 3s off; 4 sets",
    instructions: [
      "Working load auto-filled from assessment (60% max hang)",
      "4 sets to near-failure; 3 min rest between sets",
    ],
    sets: 4,
    intensity: "60% MVC",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  intermittent_hang_w7: {
    type: "intermittent_hang",
    name: "Intermittent Hang Endurance (IHE)",
    description: "60% MVC; 6 sets",
    instructions: ["Increased set count from Week 5"],
    sets: 6,
    intensity: "60% MVC",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  intermittent_hang_deload: {
    type: "intermittent_hang",
    name: "Deload IHE",
    description: "3 sets intermittent hangs",
    instructions: ["Reduced volume deload"],
    sets: 3,
    intensity: "60% MVC",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  critical_force_w6: {
    type: "critical_force",
    name: "Critical-Force Blocks",
    description: "2-3 blocks × 2 min at RPE 8-9; 7s on / 3s off",
    instructions: [
      "Slightly below all-out intensity — stable and consistent",
      "6-8 min rest between blocks",
      "Log reps and force stability late in each block",
    ],
    sets: 3,
    intensity: "RPE 8-9",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  light_bouldering: {
    type: "easy_climbing",
    name: "Light Bouldering",
    description: "8-12 easy-moderate problems; silent feet active",
    instructions: ["RPE 5-6; focus on technique, not fatigue"],
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  route_practice_w9: {
    type: "route_practice",
    name: "Route Attempts",
    description: "3 burns on goal route; learn beta",
    instructions: [
      "Fluency constraint on rehearsal burns (log stops >2s)",
      "Drop constraint on genuine send attempts",
    ],
    sets: 3,
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  route_practice_w10: {
    type: "route_practice",
    name: "Route Linking",
    description: "4 burns; link sections with rest",
    instructions: ["Full rest between burns (15-20 min)"],
    sets: 4,
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  route_practice_w11: {
    type: "route_practice",
    name: "Redpoint Attempts",
    description: "4-5 burns; prioritize sending",
    instructions: ["Go for sends; track high point and beta changes"],
    sets: 5,
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  threshold_intervals_w9: {
    type: "threshold_intervals",
    name: "Threshold Intervals",
    description: "4 × 2 min threshold efforts; RPE 7-8",
    instructions: ["4-6 min rest between repeats", "Practice pacing and shake timing"],
    sets: 4,
    reps: "2 min",
    intensity: "RPE 7-8",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  threshold_intervals_w10: {
    type: "threshold_intervals",
    name: "Threshold Intervals",
    description: "5 × 3 min threshold efforts",
    instructions: ["Increased duration per repeat"],
    sets: 5,
    reps: "3 min",
    intensity: "RPE 7-8",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  threshold_intervals_w11: {
    type: "threshold_intervals",
    name: "Threshold Intervals",
    description: "4 × 4 min (reduced volume before taper)",
    instructions: ["Longer efforts; fewer total sets"],
    sets: 4,
    reps: "4 min",
    intensity: "RPE 7-8",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  mobility_work: {
    type: "mobility",
    name: "Mobility Work",
    description: "15 min flexibility and shoulder mobility",
    instructions: ["Focus shoulders, hips, forearms"],
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  assessment_battery: {
    type: "warmup",
    name: "Assessment Battery",
    description: "Full retest: max hang, IHE, crux-after-fatigue",
    instructions: [
      "Complete full assessment battery",
      "Compare to Week 0 baseline",
    ],
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  // 3-day plan specific drills
  long_intervals_w1: {
    type: "arc_climbing",
    name: "Long Intervals + Fluency",
    description: "4 × 6 min continuous climbing; fluency constraint",
    instructions: ["No stop >2s unless at rest hold; log stop count per set"],
    sets: 4,
    reps: "6 min",
    intensity: "RPE 6-7",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  long_intervals_w2: {
    type: "arc_climbing",
    name: "Long Intervals + Fluency",
    description: "4 × 7 min",
    instructions: ["Same fluency constraint"],
    sets: 4,
    reps: "7 min",
    intensity: "RPE 6-7",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  long_intervals_w3: {
    type: "arc_climbing",
    name: "Long Intervals + Fluency",
    description: "4 × 8 min",
    instructions: ["Same fluency constraint"],
    sets: 4,
    reps: "8 min",
    intensity: "RPE 6-7",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  strength_antagonist_wed: {
    type: "max_hang",
    name: "Max Hangs + Antagonist",
    description: "3-day Wed session: max hangs then antagonist",
    instructions: [
      "Max hangs when fresh",
      "Antagonist circuit after — separated from endurance days",
    ],
    sets: 6,
    reps: "10 seconds",
    intensity: "85-93%",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  // 2-day combined session drills
  combined_strength_aerobic: {
    type: "max_hang",
    name: "Max Hangs (Session A Part 1)",
    description: "Strength first when fresh, then aerobic",
    instructions: ["Complete max hangs before aerobic work"],
    sets: 5,
    reps: "10 seconds",
    intensity: "85-90%",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  combined_aerobic_arc: {
    type: "arc_climbing",
    name: "ARC Aerobic (Session A Part 2)",
    description: "ARC after strength; RPE 4-6",
    instructions: ["Silent feet + fluency constraints"],
    sets: 2,
    reps: "15 min",
    intensity: "RPE 4-6",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },

  combined_pe_specificity: {
    type: "crux_after_fatigue",
    name: "4×4 + Crux Simulation (Session B)",
    description: "Combined power-endurance + specificity session",
    instructions: ["4×4 first while fresher, then crux simulation"],
    sets: 5,
    reps: "combined",
    intensity: "RPE 8-9",
    notes: [],
    isOptional: false,
    safetyWarnings: [],
    progressionRules: [],
  },
};

export const drillCatalog: Record<string, PEDrillDefinition> = Object.fromEntries(
  Object.entries(DRILLS).map(([id, d]) => [id, { ...d, id }])
);

export function getDrill(id: string): PEDrillDefinition | undefined {
  return drillCatalog[id];
}

export function resolveDrills(ids: string[]): PEDrillDefinition[] {
  return ids
    .map((id) => drillCatalog[id])
    .filter((d): d is PEDrillDefinition => d != null);
}
